/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
module hive.thrift.TCLIService_constants;

import thrift.base;
import thrift.codegen.base;
import thrift.util.hashset;

import hive.thrift.TCLIService_types;

immutable(HashSet!(TTypeId)) PRIMITIVE_TYPES;
immutable(HashSet!(TTypeId)) COMPLEX_TYPES;
immutable(HashSet!(TTypeId)) COLLECTION_TYPES;
immutable(string[TTypeId]) TYPE_NAMES;
immutable(string) CHARACTER_MAXIMUM_LENGTH;
immutable(string) PRECISION;
immutable(string) SCALE;

static this() {
  PRIMITIVE_TYPES = cast(immutable(HashSet!(TTypeId))) {
    HashSet!(TTypeId) v;
    v ~= cast(TTypeId)0;
    v ~= cast(TTypeId)1;
    v ~= cast(TTypeId)2;
    v ~= cast(TTypeId)3;
    v ~= cast(TTypeId)4;
    v ~= cast(TTypeId)5;
    v ~= cast(TTypeId)6;
    v ~= cast(TTypeId)7;
    v ~= cast(TTypeId)8;
    v ~= cast(TTypeId)9;
    v ~= cast(TTypeId)15;
    v ~= cast(TTypeId)16;
    v ~= cast(TTypeId)17;
    v ~= cast(TTypeId)18;
    v ~= cast(TTypeId)19;
    v ~= cast(TTypeId)20;
    v ~= cast(TTypeId)21;
    return v;
  }();

  COMPLEX_TYPES = cast(immutable(HashSet!(TTypeId))) {
    HashSet!(TTypeId) v;
    v ~= cast(TTypeId)10;
    v ~= cast(TTypeId)11;
    v ~= cast(TTypeId)12;
    v ~= cast(TTypeId)13;
    v ~= cast(TTypeId)14;
    return v;
  }();

  COLLECTION_TYPES = cast(immutable(HashSet!(TTypeId))) {
    HashSet!(TTypeId) v;
    v ~= cast(TTypeId)10;
    v ~= cast(TTypeId)11;
    return v;
  }();

  TYPE_NAMES = cast(immutable(string[TTypeId])) {
    string[TTypeId] v;
    v[cast(TTypeId)0] = "BOOLEAN";
    v[cast(TTypeId)1] = "TINYINT";
    v[cast(TTypeId)2] = "SMALLINT";
    v[cast(TTypeId)3] = "INT";
    v[cast(TTypeId)4] = "BIGINT";
    v[cast(TTypeId)5] = "FLOAT";
    v[cast(TTypeId)6] = "DOUBLE";
    v[cast(TTypeId)7] = "STRING";
    v[cast(TTypeId)8] = "TIMESTAMP";
    v[cast(TTypeId)9] = "BINARY";
    v[cast(TTypeId)10] = "ARRAY";
    v[cast(TTypeId)11] = "MAP";
    v[cast(TTypeId)12] = "STRUCT";
    v[cast(TTypeId)13] = "UNIONTYPE";
    v[cast(TTypeId)15] = "DECIMAL";
    v[cast(TTypeId)16] = "NULL";
    v[cast(TTypeId)17] = "DATE";
    v[cast(TTypeId)18] = "VARCHAR";
    v[cast(TTypeId)19] = "CHAR";
    v[cast(TTypeId)20] = "INTERVAL_YEAR_MONTH";
    v[cast(TTypeId)21] = "INTERVAL_DAY_TIME";
    return v;
  }();

  CHARACTER_MAXIMUM_LENGTH = "characterMaximumLength";

  PRECISION = "precision";

  SCALE = "scale";
}
